### PR TITLE
Basic improvements

### PR DESCRIPTION
**Pull request by thompsy**
I've made a few basic improvements here Ioannis. I'd like you to look over them and make sure you understand them. Here's a basic overview of what I've done:

- I've moved the `pom.xml` file into the main directory of the project. This is where Maven expects it to be. When you in the main directory you should be able to run `mvn compile` to build the program and then something like this to run it: `mvn compile exec:java -Dexec.mainClass="com.ewan.TaskManager.Main" -Dexec.args="--view"`
- I removed the duplicate `TaskManager.java` file that was in the main project directory. All source code should live under the `src` directory.
- I deleted the unused test file. It's good practice to only add files to Git that are actually being used. 
- I reformatted all the Java files with the formatter built into to VSCode. I don't really care how the files are formatted as long as there is a format that's applied consistently to all the files. This makes them much easier to read and understand and is good practice to get into. I'm not super-familiar with VSCode but it looks like you can set it up to format on save which would be a good idea: https://stackoverflow.com/questions/39494277/how-do-you-format-code-on-save-in-vs-code
- I reformatted the comments to be inline with standard JavaDoc format. Again, it's good practice to follow the standard patterns as it will make your life easier and will be important when other people are interacting with you code. Here's a reasonable summary of the format: https://www.baeldung.com/javadoc

Hopefully, that all makes sense! If not feel free to comment and we can discuss it. Feel free to merge this PR once you're happy.

### CODE REVIEW

**Comment by Ewan10** [comment]
I can create a merge commit. I would go for the conventional console app with command line arguments. So to correct the problem of the infinite loop I must remove the while(true) {} and on the terminal if I run: mvn compile exec:java -Dexec.mainClass="com.ewan.TaskManager.Main" -Dexec.args="--anOption" where anOption is one option? And to run it again I keep retyping the above with another option?

**Comment by thompsy** [comment]
That's right. You need to remove the `while` loop and then you can run the program with a different argument each time. 

It's helpful here to think from a user's perspective. How would someone use this program, or even better, how would you use this program? Would you want it to be on all the time or would you want to run it occasionally, for example, when a new task popped into you head, or when you had finished a task and wanted to mark it as complete.

**Comment by Ewan10** [comment]
Regarding JUnit 5 today I am reading the JUnit documentation specifically the section for writing tests. It contains many utilities. I watched this video as an example of applying tests: https://www.youtube.com/watch?v=Geq60OVyBPg. I think I will need a session to discuss what sort of test methods to apply for testing the particular public api of the TaskManager as its methods generate different type of output from that example video or other videos (they do operations on the data structure or they invoke private methods which print on the screen). 

I have recorded two test methods and I wrote the signature of five test methods without a body each one aimed to test each of the public api methods. If you give me one - two days time to think about the problem and read the JUnit doc. then let me know when to arrange a session.

**Comment by thompsy** [comment]
That's fine Ioannis. I'll create a task to add unit tests and we can keep the testing related discussion there and keep discussion here related specifically to this PR.

**Pull request merged**
